# Test prompts per "Canción de peregrino"
prompts:
  - "Qual è il tema principale di 'Canción de peregrino'?"
  - "Chi è l'autore di 'Canción de peregrino' e quali informazioni vengono fornite su di lui?"
  - "Quali sono i simboli ricorrenti in 'Canción de peregrino'?"
  - "Come viene descritto il viaggio del pellegrino nel testo?"
  - "Quali riferimenti religiosi o spirituali sono presenti in 'Canción de peregrino'?"
  - "Quali sono gli elementi stilistici caratteristici di questa poesia o canzone?"
  - "Quali emozioni vengono espresse in 'Canción de peregrino'?"
  - "Come si sviluppa la narrazione all'interno di 'Canción de peregrino'?"
  - "Quali metafore vengono utilizzate in 'Canción de peregrino' e qual è il loro significato?"
  - "Quali sono i riferimenti culturali o storici presenti nel testo?"
  - "Come viene rappresentato il concetto di cammino o pellegrinaggio nell'opera?"
  - "Quali sono le principali caratteristiche linguistiche di 'Canción de peregrino'?"
  - "Come si collega quest'opera alla tradizione letteraria del pellegrinaggio?"
  - "Quali sono i versi più significativi di 'Canción de peregrino' e perché?"
  - "Come viene trattato il tema della trasformazione personale attraverso il viaggio in questo testo?"

tests:
  - description: "Verificare la pertinenza delle risposte a Canción de peregrino"
    assert:
      - type: "language-match"
        value: "it"
      - type: "contains-any"
        value: ["pellegrino", "canción", "poesia", "cammino", "viaggio", "simboli", "spirituale"]
      
  - description: "Verificare la qualità e profondità delle risposte"
    assert:
      - type: "contains-json"
        value: |
          {
            "min_length": 150
          }
      - type: "not-contains-any"
        value: ["Non lo so", "non posso rispondere", "non ho accesso", "le mie conoscenze sono limitate"]

outputs:
  - type: "json_file"
    path: "test_output/cancion_peregrino_results.json"
  - type: "markdown_file"
    path: "test_output/cancion_peregrino_results.md"

variants:
  - name: "semantic_chunking"
    description: "Test con chunking semantico"
    config:
      chunking_strategy: "semantic"
      
  - name: "size_chunking"
    description: "Test con chunking basato su dimensione"
    config:
      chunking_strategy: "size"