# Configurazione di test per il libro "Effortless Mastery" di Kenny Werner

prompts:
  - "Qual è il concetto principale di 'Effortless Mastery' secondo Kenny Werner?"
  - "Come descrive Kenny Werner il rapporto tra musicisti e la loro arte?"
  - "Quali sono i principali ostacoli mentali che Kenny Werner identifica per i musicisti?"
  - "Quali esercizi o pratiche suggerisce Kenny Werner per sviluppare la padronanza senza sforzo?"
  - "Come tratta il libro il tema della paura durante l'esecuzione musicale?"
  - "Quali sono i quattro stadi di padronanza descritti nel libro?"
  - "Come viene definita la meditazione nel contesto dell'esecuzione musicale?"
  - "Quali sono le tecniche per liberarsi dalle autolimitazioni secondo Werner?"
  - "Come viene descritto nel libro il concetto di 'spazio' in relazione all'improvvisazione jazz?"
  - "Quali storie o aneddoti personali condivide Kenny Werner per illustrare i suoi concetti?"
  - "In che modo il concetto di 'Effortless Mastery' può essere applicato ad altre discipline oltre alla musica?"
  - "Come affronta Werner la relazione tra tecnica e libertà espressiva?"
  - "Qual è l'importanza del silenzio e dello spazio nell'improvvisazione secondo Werner?"
  - "Quali benefici psicologici derivano dall'approccio di Werner alla pratica musicale?"
  - "Come suggerisce Werner di affrontare le sessioni di pratica quotidiana?"

tests:
  - description: "Estrazione dei concetti chiave"
    assert:
      - type: "contains-any"
        value: ["mastery", "padronanza", "Werner", "musicista", "jazz", "meditazione", "improvvisazione"]
      - type: "not-contains-any"
        value: ["Non lo so", "non posso rispondere", "nessuna informazione pertinente"]
  
  - description: "Qualità della risposta"
    assert:
      - type: "contains-json"
        value: |
          {
            "min_length": 100
          }
      - type: "not-contains-any"
        value: ["Come IA", "non ho accesso", "le mie conoscenze", "Sono un'IA"]
  
  - description: "Citazione delle fonti"
    assert:
      - type: "contains-any"
        value: ["libro", "testo", "capitolo", "Werner afferma", "secondo Werner", "pagina"]
  
evaluations:
  - promptName: "Qual è il concetto principale di 'Effortless Mastery' secondo Kenny Werner?"
    expected: |
      La risposta dovrebbe descrivere il concetto fondamentale dell'approccio di Werner alla padronanza musicale senza sforzo,
      che si concentra sulla liberazione dalla paura, dall'ego e dal giudizio mentre si suona.
    criteria:
      - "La risposta deve spiegare l'idea della 'padronanza senza sforzo'"
      - "La risposta deve menzionare l'aspetto meditativo e di consapevolezza del metodo"
      - "La risposta deve menzionare come questo approccio differisce dai metodi tradizionali di pratica musicale"
  
  - promptName: "Come descrive Kenny Werner il rapporto tra musicisti e la loro arte?"
    expected: |
      La risposta dovrebbe esplorare la visione di Werner della relazione spesso problematica tra musicisti e la loro arte,
      inclusi i temi dell'ego, dell'autovalutazione e del perfezionismo.
    criteria:
      - "La risposta deve affrontare il tema dell'ego durante l'esecuzione musicale"
      - "La risposta deve descrivere la critica di Werner all'approccio ossessivo alla pratica"
      - "La risposta deve includere la prospettiva spirituale di Werner sulla pratica musicale"
      
  - promptName: "Quali sono i quattro stadi di padronanza descritti nel libro?"
    expected: |
      La risposta dovrebbe elencare e descrivere i quattro stadi di padronanza che Werner delinea nel libro.
    criteria:
      - "La risposta deve identificare correttamente tutti e quattro gli stadi"
      - "La risposta deve spiegare le caratteristiche di ciascuno stadio"
      - "La risposta deve descrivere come questi stadi si collegano al concetto di padronanza senza sforzo"
      
  - promptName: "In che modo il concetto di 'Effortless Mastery' può essere applicato ad altre discipline oltre alla musica?"
    expected: |
      La risposta dovrebbe esplorare come i principi di Werner possono essere utilizzati in altre arti o discipline come la pittura,
      la scrittura, lo sport o anche nella vita quotidiana.
    criteria:
      - "La risposta deve identificare le dimensioni universali dell'approccio di Werner"
      - "La risposta deve dare esempi concreti di applicazione in altri ambiti"
      - "La risposta deve mantenere la coerenza con i principi fondamentali del libro"
      
  - promptName: "Come affronta Werner la relazione tra tecnica e libertà espressiva?"
    expected: |
      La risposta dovrebbe analizzare come Werner affronta il paradosso tra la necessità di padronanza tecnica 
      e la libertà espressiva necessaria per l'arte autentica.
    criteria:
      - "La risposta deve descrivere l'approccio di Werner all'equilibrio tra tecnica e espressione"
      - "La risposta deve spiegare come la tecnica può diventare sia un ostacolo che un veicolo per l'espressione"
      - "La risposta deve citare la visione di Werner su come trascendere la tecnica"

outputs:
  - type: "json_file"
    path: "test_output/kenny_werner_test_results.json"
  - type: "markdown_file"
    path: "test_output/kenny_werner_test_results.md"

variants:
  - name: "semantic_chunking"
    description: "Test con chunking semantico"
    config:
      chunking_strategy: "semantic"
      
  - name: "size_chunking"
    description: "Test con chunking basato su dimensione"
    config:
      chunking_strategy: "size"